# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291c524933d5247076a9d36673ed334f21b587414fccd72982df66100c713a0a658f8d91affbe8db2ae979da3f8de6d03ec7f942573f8d28fd860269d57eeff2

test:
  secret_key_base: 13f58cf1c07d81d05c6b58a18ffe1447f6bcd01a15a3f5aa69c50203c124b0fc6adfc322daa28cfb267c81b6cc05fa9303e4e6417c7f1fcb50745ba1f20c480a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
